version: "3"

services:
  trojan:
    image: teddysun/trojan-go
    container_name: trojan
    restart: unless-stopped
    ports:
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./trojan/config:/etc/trojan-go
      - ./ssl:/ssl
    depends_on:
      - caddy

  caddy:
    image: caddy
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./wwwroot:/usr/src
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./ssl:/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory